export const lorem = `Lorem Ipsum
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac porttitor justo. Nam a tempus ipsum. Curabitur malesuada nibh lectus, eget fringilla orci porttitor consequat. Vivamus suscipit vel lectus sollicitudin semper. Duis maximus ultrices elit, nec bibendum ipsum. Ut condimentum eu nisi id tempor. Donec lacinia lorem sit amet dui tincidunt efficitur. Sed vitae erat vitae turpis mollis auctor. In hac habitasse platea dictumst. Duis feugiat scelerisque elit eu bibendum.

Etiam nec tortor at purus suscipit molestie. Pellentesque nulla nisi, consectetur ut fermentum in, interdum at mauris. Suspendisse potenti. Nulla ac sagittis nisi. Mauris facilisis dictum ligula a molestie. Fusce hendrerit, arcu ac ultricies dictum, sapien turpis vulputate metus, eu molestie arcu neque eget lacus. Suspendisse sit amet condimentum dolor. Vestibulum eu turpis pretium, hendrerit risus sed, ornare mi. Aenean id nisl lacus. Suspendisse id vehicula justo. Donec placerat dapibus pellentesque. Morbi vel sem eu lorem rutrum feugiat. Nulla facilisi. Suspendisse vulputate dolor ac nulla placerat consequat. Nullam ultrices dolor mauris.

Suspendisse potenti. Nulla vestibulum interdum mi ac aliquet. Nunc ornare risus nec libero pulvinar, id gravida sapien consequat. Donec sagittis dui nec ligula pharetra sollicitudin. Phasellus ac sem sapien. Donec pellentesque nulla eu odio interdum, et volutpat felis pretium. Duis molestie in lacus ac consequat.

Nam rutrum eros vel velit rhoncus, in pellentesque nulla rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris eget pretium tortor, ac convallis dolor. Nullam id sagittis massa. Proin eleifend consectetur sapien, quis viverra lectus posuere nec. Sed luctus, augue eget vestibulum tincidunt, lacus quam laoreet orci, ut porttitor elit arcu at ligula. Pellentesque aliquet mi dolor, eu pellentesque enim tristique id. Nam ligula nunc, fermentum vel fermentum in, ultrices fermentum ipsum. Quisque auctor lectus quis erat consequat bibendum. In feugiat turpis non vehicula convallis. Donec suscipit libero enim, et cursus nisl cursus eu.

Proin cursus augue tincidunt metus suscipit, eu hendrerit ligula euismod. Suspendisse lacinia est eu metus commodo, nec consequat augue fermentum. Vestibulum pellentesque, ipsum ut placerat pellentesque, leo erat ultricies enim, quis lacinia nunc nunc sollicitudin arcu. Praesent rhoncus, dolor imperdiet molestie tempor, mi dui aliquet turpis, a varius mauris odio at tellus. Donec placerat, felis vitae fringilla egestas, tellus eros tempus arcu, et vestibulum velit sem nec neque. Curabitur tellus justo, viverra hendrerit nunc vitae, malesuada iaculis nisl. Aenean vitae mi velit. Quisque quis justo ut urna mattis hendrerit. Morbi facilisis elit ante. Mauris ac sapien id orci cursus pellentesque quis quis ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque efficitur, purus sed molestie auctor, justo mauris semper tortor, vitae efficitur leo odio nec ligula. In vestibulum risus nunc, ac pellentesque orci accumsan suscipit.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut viverra ligula eros, sit amet viverra felis tempus at. Suspendisse mauris arcu, facilisis vitae sodales nec, commodo nec odio. Donec eros ex, hendrerit convallis ornare nec, ullamcorper a nunc. Fusce et odio vel erat ornare pretium. Aenean neque urna, gravida nec ligula et, mollis facilisis mauris. Morbi sit amet justo odio. Maecenas sapien mi, hendrerit in pretium at, ultrices nec libero. Praesent vel turpis sollicitudin, lacinia ligula viverra, ornare lacus. Donec a erat fermentum, eleifend dolor sit amet, vulputate sem.

Aliquam aliquet placerat ligula rutrum tristique. Pellentesque placerat pulvinar fermentum. Praesent pellentesque enim sed ante vestibulum, sed ultricies arcu blandit. Pellentesque rhoncus sagittis mauris nec lobortis. Nullam eget elit libero. Praesent lorem lorem, eleifend et aliquet quis, scelerisque nec sem. Nunc sit amet orci venenatis nisi pharetra ultrices non nec nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti.

Ut purus velit, egestas at pretium et, feugiat sed arcu. Nulla malesuada auctor nunc, quis interdum ante hendrerit vel. Maecenas quis molestie risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et libero felis. Nunc iaculis ornare congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean commodo est ante, a tempor erat posuere at. Nulla facilisi. Curabitur semper ac justo ac gravida. Cras eu nisi eros. In consectetur varius euismod.

Ut congue ipsum a sem varius, quis convallis diam rutrum. Cras at ex in purus efficitur iaculis. Phasellus aliquam nisl risus, sit amet efficitur libero rutrum sit amet. Aenean eget faucibus ante, a auctor augue. Fusce sollicitudin molestie justo, sed dignissim lorem posuere vitae. Fusce a pretium quam. Nunc magna ante, sollicitudin in tristique et, fermentum a massa. Praesent quis maximus ex. Fusce sollicitudin dictum tortor, nec semper lectus porttitor eu. Aliquam pretium vitae est quis semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc pharetra quam sit amet odio ullamcorper semper. Phasellus nec sem dolor. Integer convallis ante leo, et sagittis turpis sollicitudin ac. Maecenas commodo ipsum eget feugiat facilisis. Aliquam mattis tortor non tristique consequat.

Curabitur euismod ac ipsum a eleifend. Morbi luctus lacus in tellus consectetur, vitae vehicula massa eleifend. Fusce congue, turpis ac ornare ultricies, urna enim porta enim, ac congue eros eros vitae dui. Mauris vel sapien pulvinar, viverra ante id, ornare lorem. Suspendisse quis luctus mauris, vitae consectetur sem. Proin a sodales mi. Proin rhoncus erat ac magna venenatis ultrices. Suspendisse libero ex, venenatis sed lobortis et, malesuada nec arcu.

Nulla condimentum orci lectus, eu volutpat sem ultricies at. Aliquam vestibulum tortor sit amet lorem aliquet, eget vulputate leo pulvinar. Vivamus sit amet felis sed mi vestibulum placerat. Curabitur imperdiet maximus neque, finibus sagittis mi pharetra a. Etiam ac dolor sit amet nisl elementum porta ac accumsan sapien. Proin ultricies malesuada ipsum, nec consequat metus tempus eu. Cras congue id diam fringilla semper. Vestibulum in metus a lacus viverra posuere. Sed mollis, odio nec aliquam interdum, diam augue faucibus dolor, non ultricies lectus lorem id massa.

Fusce eget libero lacinia, dictum libero in, imperdiet tellus. Cras et ligula a augue suscipit volutpat. Nam condimentum dui laoreet pharetra blandit. Fusce vulputate libero quis turpis vehicula consectetur. Nullam eget tempor metus. Vestibulum aliquam porttitor lorem sit amet dignissim. Praesent interdum velit mi, in varius turpis ultricies sit amet. Nunc sit amet semper velit, nec blandit velit. Mauris nec laoreet mi. Duis pellentesque quam eu libero consequat, et convallis nisl tempus. Nulla a est et libero volutpat malesuada sed in arcu. Phasellus tincidunt condimentum varius. Vestibulum commodo nec tellus eleifend gravida. Praesent pulvinar, turpis eget semper pharetra, urna massa vestibulum sem, in tincidunt justo neque in odio. Nam malesuada malesuada turpis, in bibendum massa varius sit amet. Fusce sollicitudin facilisis hendrerit.

Aenean luctus enim eu nunc condimentum pellentesque. Aenean pulvinar leo id gravida placerat. Maecenas pellentesque mi lectus, ac vulputate ligula aliquam vel. Nunc et erat nec nibh tempus luctus vel non magna. Quisque at imperdiet mauris. Aliquam erat volutpat. Ut vel ex eget augue congue molestie. Vivamus vitae commodo metus. Sed fringilla metus ac ligula iaculis feugiat. Praesent pulvinar, nisi eu vestibulum sagittis, velit lectus fermentum enim, quis commodo orci lectus sit amet ante. Aenean id tristique erat. Mauris in tellus et leo fringilla aliquet. Fusce mollis sapien a laoreet laoreet. Vestibulum mollis ante ante, non fringilla dolor hendrerit id. Nullam sed justo fringilla, gravida tellus eu, gravida est. Phasellus dapibus et eros ac efficitur.

Nullam congue sed est quis pretium. Donec laoreet aliquet ligula eleifend finibus. Etiam sit amet velit vel purus iaculis mollis. Sed pharetra urna mi, sit amet consequat leo venenatis sit amet. Quisque posuere urna eget ligula porta eleifend. Cras finibus massa in quam feugiat, nec porttitor turpis interdum. Suspendisse tincidunt in dui rhoncus molestie. Fusce lobortis augue non nisi consequat porttitor. In sagittis porta lectus, in aliquet nulla blandit vitae. Mauris eget hendrerit odio, vitae aliquam nulla. Vestibulum et lectus odio.

Nam consequat hendrerit maximus. Nulla facilisi. Fusce id sem sollicitudin, egestas enim ut, malesuada sapien. Mauris eu magna id tortor tempus tincidunt. Ut ut faucibus nibh. Sed accumsan dignissim diam, non pulvinar sapien ultricies pharetra. Nunc eget congue ligula, vitae fringilla ligula. Nulla finibus tincidunt sagittis. Donec turpis augue, interdum eu consectetur et, tincidunt eu arcu. Praesent volutpat sagittis elit a congue. Nunc eu pellentesque purus, sit amet dignissim arcu. Proin auctor pulvinar sapien, vulputate vulputate purus dignissim sit amet. Aenean blandit dignissim est, in convallis lorem pretium in. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ut sem orci.

Curabitur id sagittis nisl, sed venenatis elit. Praesent non elementum lorem. Integer est nunc, efficitur ac mauris et, tincidunt eleifend erat. Maecenas sed vulputate diam, sed porttitor ipsum. Ut porttitor dictum purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquam, augue ac blandit varius, risus erat consectetur erat, in euismod lectus augue vitae nulla. Suspendisse malesuada erat lacus, et tincidunt arcu maximus sed. Fusce mattis urna id sapien posuere, vitae laoreet odio porttitor. Nam ac elit rutrum, cursus justo in, ultrices quam. Quisque posuere leo eu varius sollicitudin. Maecenas maximus ut tortor in feugiat.

In euismod urna eros, eu tempor leo convallis eu. Integer molestie lectus id arcu elementum, blandit semper libero commodo. Sed feugiat sit amet mauris et pulvinar. Vivamus feugiat mauris nec massa viverra convallis. Donec vulputate placerat velit id suscipit. Quisque ut ullamcorper purus, vel ullamcorper nisl. Nulla facilisi. Cras tincidunt dolor velit, nec varius nisl iaculis nec. Nulla tempus, ipsum vel pretium convallis, turpis massa tempor eros, vel condimentum dui tortor at neque. Nunc quis justo et urna ultrices elementum non eget odio.

Donec condimentum erat placerat ipsum venenatis feugiat. Curabitur placerat tristique leo, ac vulputate tortor scelerisque sit amet. Integer quis risus vitae ante iaculis viverra. Vestibulum ac pharetra diam. Cras quis malesuada augue. Proin id gravida nisl. In tempus tortor lacus, vel porta purus imperdiet quis. Suspendisse eget viverra risus. Cras molestie aliquam dolor id pulvinar. Mauris nec accumsan nibh, a porta tellus. Aenean porta augue ornare tortor hendrerit accumsan.

In at vestibulum purus. Integer imperdiet placerat metus, a finibus velit vestibulum vitae. Praesent fermentum odio sed tellus pulvinar consequat. Curabitur lorem odio, pulvinar consequat fermentum et, congue eget massa. Donec sed imperdiet felis, sit amet efficitur sem. Suspendisse blandit vitae enim imperdiet aliquet. Aliquam erat volutpat. Integer tempus sed massa et finibus. Sed tempus ac ligula id commodo. Vivamus et dui dictum, ornare mauris nec, facilisis neque.

Maecenas ipsum metus, sodales ut mauris eu, accumsan suscipit neque. Aenean quis metus tortor. Integer purus lacus, hendrerit eu pulvinar eu, lobortis ac ex. Vestibulum eu lacus iaculis, ultrices nulla at, ullamcorper justo. Sed eu bibendum nisi. Morbi auctor dignissim nibh pulvinar rutrum. Nullam accumsan luctus imperdiet. Nulla ultrices dapibus dolor, vitae molestie velit mollis a. Suspendisse luctus velit posuere sem posuere, vel dignissim mi finibus. Duis ac lacus tempor, dignissim dui eu, iaculis turpis. Suspendisse tellus nulla, lacinia a molestie ac, interdum at augue. Duis posuere a massa ac vulputate. Nullam vestibulum, ante laoreet maximus aliquet, magna augue ultricies enim, sit amet accumsan tortor turpis sed dui. Praesent feugiat, eros ut ultricies imperdiet, quam risus auctor ipsum, laoreet accumsan urna erat vel dui. Pellentesque massa erat, interdum id nisi in, lacinia placerat felis.`

//https://stackoverflow.com/questions/70790519/tailwindcss-how-can-i-fix-a-header-footer-to-the-screen-while-keeping-scrolla